- name: playbook for debug
  hosts: all
  vars: 
   URL: "www.ganesh.com"
  tasks:
    - name: print hello world
      debug:
        msg: "Please visit {{ URL }}"
    - name: print hello world
      debug:
       msg: "Please visit {{ URL }}"
    - name: print hello world
      debug:
       msg: "Please visit {{ URL }}"
      vars:
        URL: "local.cloudblitz.in"